### ISSUE TITLE
Hello, plug-in startup error

### ISSUE THREAD

**Issue by liutingfenga** [byteful/PictureAds#1]
``[17:13:34] [Netty Server IO #2/INFO]: [PictureAds] Enabling PictureAds v1.0.4
[17:13:34] [Netty Server IO #2/ERROR]: Error occurred while enabling PictureAds v1.0.4 (Is it up to date?)
java.lang.NoClassDefFoundError: redempt/redlib/commandmanager/Messages
        at me.byteful.plugin.pictureads.PictureAdsPlugin.loadMessages(PictureAdsPlugin.java:77) ~[?:?]
        at me.byteful.plugin.pictureads.PictureAdsPlugin.onEnable(PictureAdsPlugin.java:59) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) ~[JavaPluginLoader.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[SimplePluginManager.class:git-CatServer-1.12.2-dae70adc]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[%5B插件管理%5DPlugManX_2.2.5.jar:?]
        at cn.apisium.nekomaid.builtin.Plugins.lambda$null$1(Plugins.java:77) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.Client.lambda$onWithAck$1(Client.java:81) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.emitter.Emitter.emit(Emitter.java:123) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onEvent(SocketIoSocket.java:304) ~[%5B网页 管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onPacket(SocketIoSocket.java:324) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$1(SocketIoClient.java:153) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.parser.IOParser$Decoder.add(IOParser.java:101) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$2(SocketIoClient.java:161) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.emitter.Emitter.emit(Emitter.java:123) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.emit(EngineIoSocket.java:185) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.onPacket(EngineIoSocket.java:395) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.lambda$setTransport$10(EngineIoSocket.java:300) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.emitter.Emitter.emit(Emitter.java:123) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onPacket(Transport.java:104) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onData(Transport.java:113) ~[%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.transport.WebSocket.lambda$new$0(WebSocket.java:27) ~[%5B 网页管理%5DNekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.emitter.Emitter.emit(Emitter.java:123) [%5B网页管理%5DNekoMaid.jar:?]
        at cn.apisium.netty.engineio.EngineIoHandler.channelRead0(EngineIoHandler.java:92) [%5B网页管理%5DNekoMaid.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [MessageToMessageDecoder.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [ChannelInboundHandlerAdapter.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [DefaultChannelPipeline$HeadContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [DefaultChannelPipeline.class:4.1.24.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [AbstractNioByteChannel$NioByteUnsafe.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [NioEventLoop.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [NioEventLoop.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [NioEventLoop.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [NioEventLoop.class:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [SingleThreadEventExecutor$5.class:4.1.24.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.ClassNotFoundException: redempt.redlib.commandmanager.Messages
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:141) ~[PluginClassLoader.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-dae70adc]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 52 more
Caused by: java.lang.ClassNotFoundException: redempt.redlib.commandmanager.Messages
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[PluginClassLoader.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-dae70adc]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 52 more

**Comment by byteful** [comment]
Where did you get the plugin JAR from? This should be shaded into the plugin, so if you tried to build it yourself, you need to make sure you are using the 'shadowJar' task.
